#ifndef DEFINITIONS_H
#define DEFINITIONS_H

enum RplCode {
  NONE = 0xff,
  DIS = 0x00,
  DIO = 0x01,
  DAO = 0x02,
  DAO_ACK = 0x03
};

#ifndef HEX_BUFFER_OCTETS_IN_GROUP
    #define HEX_BUFFER_OCTETS_IN_GROUP 4
#endif

#ifndef HEX_BUFFER_GROUPS_IN_LINE
    #define HEX_BUFFER_GROUPS_IN_LINE 2
#endif

#define HEX_BUFFER_OCTETS_IN_LINE (HEX_BUFFER_OCTETS_IN_GROUP * HEX_BUFFER_GROUPS_IN_LINE)


#endif // DEFINITIONS_H
