#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#ifndef HEX_BUFFER_OCTETS_IN_GROUP
  #define HEX_BUFFER_OCTETS_IN_GROUP 4
#endif

#ifndef HEX_BUFFER_GROUPS_IN_LINE
  #define HEX_BUFFER_GROUPS_IN_LINE 2
#endif

#define HEX_BUFFER_OCTETS_IN_LINE (HEX_BUFFER_OCTETS_IN_GROUP * HEX_BUFFER_GROUPS_IN_LINE)


#endif // DEFINITIONS_H
